# Generated by Django 5.2.5 on 2026-01-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_healthprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='sugar_type',
            field=models.CharField(choices=[('Fasting', 'Fasting'), ('Random', 'Random')], default='Normal', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='blood_pressure',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='height',
            field=models.FloatField(help_text='Height in cm'),
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='weight',
            field=models.FloatField(help_text='Weight in kg'),
        ),
    ]
