# Generated by Django 5.2.5 on 2026-01-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0003_healthprofile_sugar_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthprofile',
            old_name='sugar_type',
            new_name='sugar_test_type',
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='sugar_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Prediabetes', 'Prediabetes'), ('Diabetes', 'Diabetes')], default='Normal', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthprofile',
            name='sugar_level',
            field=models.FloatField(help_text='mg/dL'),
        ),
    ]
