# Generated by Django 6.0.2 on 2026-03-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_add_medical_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='extracted_metrics',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
