# Generated by Django 6.0.2 on 2026-03-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_add_extracted_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='diet_plan',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='lifestyle_plan',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='workout_plan',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
