# Generated by Django 6.0.2 on 2026-03-14 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0007_add_structured_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='last_streak_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='total_activities_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserActivityTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('workout_completed', models.BooleanField(default=False)),
                ('diet_followed', models.BooleanField(default=False)),
                ('medicine_taken', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
