# Generated by Django 6.0.2 on 2026-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
